import type { ModelContextTool } from '@mcp-b/webmcp-types'
import { audioEngine } from '../audio/audioEngine'
import { applyProjectAction, findClip, findTrack } from '../domain/projectActions'
import type { EditProposal, Project, ProjectAction, ProposalAction, Selection } from '../domain/types'
import { ProjectError } from '../domain/types'
import { useWavecraftStore } from '../store/wavecraftStore'

type Args = Record<string, unknown>
type Tool = ModelContextTool<Args, unknown> & { inputSchema: NonNullable<ModelContextTool<Args, unknown>['inputSchema']> }

const emptySchema = { type: 'object' as const, properties: {}, additionalProperties: false }
const stringField = (description: string) => ({ type: 'string', description })
const numberField = (description: string, minimum = 0) => ({ type: 'number', minimum, description })
const idSchema = (field: string, description: string) => ({ type: 'object' as const, properties: { [field]: stringField(description) }, required: [field], additionalProperties: false })
const rangeSchema = { type: 'object' as const, properties: { start: numberField('Range start in seconds from the project timeline.'), end: numberField('Range end in seconds; must be greater than start.') }, required: ['start', 'end'], additionalProperties: false }

function serializeError(error: unknown) {
  const projectError = error instanceof ProjectError ? error : new ProjectError('UNEXPECTED_ERROR', error instanceof Error ? error.message : 'Unexpected tool error')
  return { success: false, error: projectError.code, message: projectError.message, ...projectError.details }
}

function safe(name: string, handler: (args: Args) => unknown | Promise<unknown>) {
  return async (args: Args) => {
    try {
      const result = await handler(args)
      useWavecraftStore.getState().recordToolCall({ name, success: true, summary: typeof result === 'object' && result && 'summary' in result ? String((result as { summary: unknown }).summary) : 'Completed' })
      return result
    } catch (error) {
      const result = serializeError(error)
      useWavecraftStore.getState().recordToolCall({ name, success: false, summary: result.message })
      return result
    }
  }
}

function tool(name: string, title: string, description: string, inputSchema: Tool['inputSchema'], handler: (args: Args) => unknown | Promise<unknown>, readOnly = false): Tool {
  return { name, title, description, inputSchema, annotations: readOnly ? { readOnlyHint: true } : undefined, execute: safe(name, handler) }
}

function projectSummary(project: Project) {
  return {
    id: project.id, name: project.name, schemaVersion: project.schemaVersion, revision: project.revision,
    duration: project.duration, sampleRate: project.sampleRate, trackCount: project.tracks.length,
    clipCount: project.tracks.reduce((sum, track) => sum + track.clips.length, 0),
    markerCount: project.markers.length, lockCount: project.locks.length,
    pendingProposalCount: project.proposals.filter((proposal) => proposal.status === 'pending').length,
    updatedAt: project.updatedAt,
  }
}

function exactSelection(selection: Selection, project: Project) {
  if (selection.kind === 'clip') return { ...selection, clips: selection.clipIds.map((id) => findClip(project, id).clip) }
  if (selection.kind === 'track') return { ...selection, tracks: selection.trackIds.map((id) => findTrack(project, id)) }
  if (selection.kind === 'marker') return { ...selection, markers: selection.markerIds.map((id) => project.markers.find((marker) => marker.id === id)).filter(Boolean) }
  if (selection.kind === 'range') {
    return {
      ...selection, duration: selection.end - selection.start,
      intersectingClips: project.tracks.flatMap((track) => track.clips.filter((clip) => clip.timelineStart < selection.end && clip.timelineStart + clip.duration > selection.start).map((clip) => ({ id: clip.id, trackId: track.id, start: clip.timelineStart, end: clip.timelineStart + clip.duration }))),
      intersectingLocks: project.locks.filter((lock) => lock.kind === 'range' && selection.start < (lock.end ?? 0) && selection.end > (lock.start ?? 0)),
    }
  }
  return selection
}

function readNumber(args: Args, key: string) {
  const value = args[key]
  if (typeof value !== 'number' || !Number.isFinite(value)) throw new ProjectError('INVALID_ARGUMENT', `${key} must be a finite number.`, { field: key, received: value })
  return value
}

function readString(args: Args, key: string) {
  const value = args[key]
  if (typeof value !== 'string' || !value.trim()) throw new ProjectError('INVALID_ARGUMENT', `${key} must be a non-empty string.`, { field: key, received: value })
  return value
}

function actionLabel(action: ProjectAction) {
  switch (action.type) {
    case 'ripple_delete_range': return `Ripple delete ${(action.end - action.start).toFixed(2)}s at ${action.start.toFixed(2)}s`
    case 'set_track_gain': return `Set ${action.trackId} gain to ${action.gainDb > 0 ? '+' : ''}${action.gainDb} dB`
    case 'set_clip_gain': return `Set ${action.clipId} gain to ${action.gainDb > 0 ? '+' : ''}${action.gainDb} dB`
    case 'move_clip': return `Move ${action.clipId} to ${action.timelineStart.toFixed(2)}s`
    case 'split_clip': return `Split ${action.clipId} at ${action.time.toFixed(2)}s`
    case 'delete_clip': return `Delete ${action.clipId}`
    default: return action.type.replaceAll('_', ' ')
  }
}

const allowedPlanActions = new Set<ProjectAction['type']>(['split_clip', 'trim_clip_start', 'trim_clip_end', 'set_clip_fades', 'move_clip', 'delete_clip', 'set_clip_gain', 'set_track_gain', 'set_track_pan', 'ripple_delete_range', 'add_marker'])

function parsePlanActions(args: Args): ProjectAction[] {
  const raw = args.actions
  if (!Array.isArray(raw) || raw.length === 0) throw new ProjectError('INVALID_EDIT_PLAN', 'actions must be a non-empty array.')
  if (raw.length > 40) throw new ProjectError('EDIT_PLAN_TOO_LARGE', 'A single edit plan may contain at most 40 actions.', { actionCount: raw.length })
  return raw.map((item, index) => {
    if (!item || typeof item !== 'object' || !('type' in item) || typeof item.type !== 'string' || !allowedPlanActions.has(item.type as ProjectAction['type'])) {
      throw new ProjectError('UNSUPPORTED_PLAN_ACTION', `Action ${index + 1} has an unsupported type.`, { index, allowedTypes: [...allowedPlanActions] })
    }
    return item as ProjectAction
  })
}

function simulateActions(project: Project, actions: ProjectAction[]) {
  let simulated = project
  for (const action of actions) simulated = applyProjectAction(simulated, action, 'agent')
  return simulated
}

function planProposal(project: Project, actions: ProjectAction[], title: string, description: string): EditProposal {
  const simulated = simulateActions(project, actions)
  const proposalActions: ProposalAction[] = actions.map((action, index) => ({
    id: `proposal_action_${project.revision + 1}_${index + 1}`, action, label: actionLabel(action),
    start: action.type === 'ripple_delete_range' ? action.start : action.type === 'split_clip' ? action.time : undefined,
    end: action.type === 'ripple_delete_range' ? action.end : undefined, status: 'pending',
  }))
  return { id: `proposal_plan_${project.revision + 1}_${Date.now()}`, title, description, createdAt: new Date().toISOString(), status: 'pending', originalDuration: project.duration, proposedDuration: simulated.duration, actions: proposalActions, rationale: ['All IDs, timestamps, and ranges validated against the live project.', `${project.locks.length} human constraint${project.locks.length === 1 ? '' : 's'} enforced.`, 'The plan is atomic when applied and creates one undo checkpoint.'] }
}

export function createWavecraftTools(): Tool[] {
  return [
    tool('get_app_capabilities', 'Get Wavecraft capabilities', 'Call first to learn the real editor features, safety model, supported audio operations, and current WebMCP tool categories. Read-only.', emptySchema, () => ({ success: true, app: 'Wavecraft', version: '0.1.0', thesis: 'Humans edit the waveform; agents edit the same project through deterministic tools.', capabilities: { audio: ['multitrack playback', 'non-destructive clips', 'WAV mixdown', 'project JSON'], context: ['time-range selection', 'clip selection', 'track selection', 'playhead', 'timeline view'], safety: ['hard human locks', 'propose-first significant edits', 'atomic proposal application', 'undo/redo', 'manual override tracking'], analysis: ['peak', 'RMS', 'clipping', 'silence', 'speaker level comparison'] }, significantEditsDefault: 'proposal', locksAlwaysOverrideDirectMode: true }), true),
    tool('inspect_context', 'Inspect live editing context', 'Use this before interpreting words like “this”, “here”, “selected”, or “keep my edit”. Returns the exact live human selection, playhead, timeline view, hard constraints, project revision, pending proposals, and manual overrides. Read-only.', emptySchema, () => { const state = useWavecraftStore.getState(); return { success: true, project: projectSummary(state.project), selection: exactSelection(state.selection, state.project), playhead: state.playback.playhead, playback: state.playback.status, timelineView: state.view, agentEditingMode: state.agentMode, locks: state.project.locks, manualOverrides: state.project.tracks.flatMap((track) => track.clips.filter((clip) => clip.manualRevision > 0).map((clip) => ({ clipId: clip.id, trackId: track.id, revision: clip.manualRevision, gainDb: clip.gainDb }))), pendingProposals: state.project.proposals.filter((proposal) => proposal.status === 'pending').map((proposal) => ({ id: proposal.id, title: proposal.title, actions: proposal.actions.length })) } }, true),
    tool('inspect_project', 'Inspect project', 'Returns structured project metadata, all track summaries, markers, regions, locks, proposals, and analysis notes without raw audio samples. Read-only.', emptySchema, () => { const project = useWavecraftStore.getState().project; return { success: true, project: projectSummary(project), tracks: project.tracks.map((track) => ({ ...track, clips: track.clips.map((clip) => ({ ...clip, end: clip.timelineStart + clip.duration })) })), markers: project.markers, regions: project.regions, locks: project.locks, proposals: project.proposals, analysis: project.analysis } }, true),
    tool('inspect_selection', 'Inspect human selection', 'Use whenever the user says “this”, “only this section”, “selected”, or refers to a visual choice. Returns exact timestamps or object IDs plus intersecting clips and locks. Read-only.', emptySchema, () => { const state = useWavecraftStore.getState(); return { success: true, selection: exactSelection(state.selection, state.project), projectRevision: state.project.revision } }, true),
    tool('get_current_constraints', 'Get human constraints', 'Returns every hard lock and manual override. Agent actions may never silently override these constraints, even in Direct mode. Read-only.', emptySchema, () => { const project = useWavecraftStore.getState().project; return { success: true, locks: project.locks, lockedTracks: project.tracks.filter((track) => track.locked).map((track) => track.id), lockedClips: project.tracks.flatMap((track) => track.clips.filter((clip) => clip.locked).map((clip) => clip.id)), manualOverrides: project.tracks.flatMap((track) => track.clips.filter((clip) => clip.manualRevision > 0).map((clip) => ({ clipId: clip.id, manualRevision: clip.manualRevision }))) } }, true),
    tool('list_tracks', 'List tracks', 'Lists stable track IDs and mix state. Use IDs from this result in later calls. Read-only.', emptySchema, () => ({ success: true, tracks: useWavecraftStore.getState().project.tracks.map((track, index) => ({ id: track.id, index, name: track.name, role: track.role, gainDb: track.gainDb, pan: track.pan, muted: track.muted, solo: track.solo, locked: track.locked, clipCount: track.clips.length })) }), true),
    tool('inspect_track', 'Inspect track', 'Returns complete structured state for one track, including stable clip IDs. Read-only.', idSchema('track_id', 'Stable track ID from list_tracks.'), (args) => { const track = findTrack(useWavecraftStore.getState().project, readString(args, 'track_id')); return { success: true, track } }, true),
    tool('list_clips', 'List clips', 'Lists all clips, optionally filtered by track_id. Returns exact timeline/source positions. Read-only.', { type: 'object', properties: { track_id: { type: 'string', description: 'Optional stable track ID.' } }, additionalProperties: false }, (args) => { const project = useWavecraftStore.getState().project; const tracks = typeof args.track_id === 'string' ? [findTrack(project, args.track_id)] : project.tracks; return { success: true, clips: tracks.flatMap((track) => track.clips.map((clip) => ({ ...clip, end: clip.timelineStart + clip.duration, trackName: track.name }))) } }, true),
    tool('inspect_clip', 'Inspect clip', 'Returns complete non-destructive edit state and source information for one clip. Read-only.', idSchema('clip_id', 'Stable clip ID from list_clips.'), (args) => { const located = findClip(useWavecraftStore.getState().project, readString(args, 'clip_id')); return { success: true, clip: located.clip, track: { id: located.track.id, name: located.track.name }, end: located.clip.timelineStart + located.clip.duration } }, true),
    tool('get_edit_history', 'Get edit history', 'Returns current revision, undo/redo availability, and applied agent actions. Read-only.', emptySchema, () => { const state = useWavecraftStore.getState(); return { success: true, revision: state.project.revision, undoDepth: state.historyPast.length, redoDepth: state.historyFuture.length, agentChanges: state.project.agentChanges } }, true),
    tool('get_agent_change_history', 'Get agent changes', 'Returns structured metadata for every applied agent edit, including originating tool, explanation, affected objects, proposal, and reversibility. Read-only.', emptySchema, () => ({ success: true, changes: useWavecraftStore.getState().project.agentChanges }), true),

    tool('get_playback_state', 'Get playback state', 'Returns playhead, playback status, loop, and project duration. Read-only.', emptySchema, () => { const state = useWavecraftStore.getState(); return { success: true, ...state.playback, duration: state.project.duration } }, true),
    tool('set_playhead', 'Set playhead', 'Move the shared human/agent playhead to an exact project time. This does not edit audio.', { type: 'object', properties: { time: numberField('Destination in seconds.') }, required: ['time'], additionalProperties: false }, (args) => { const state = useWavecraftStore.getState(); const time = readNumber(args, 'time'); if (time > state.project.duration) throw new ProjectError('INVALID_TIME', 'Playhead time exceeds project duration.', { time, projectDuration: state.project.duration }); state.setPlayhead(time); return { success: true, operation: 'set_playhead', playhead: time } }),
    tool('play', 'Play project', 'Start real audio playback from the current playhead using the current non-destructive edit state.', emptySchema, async () => { const state = useWavecraftStore.getState(); await audioEngine.play(state.project, state.playback.playhead, () => { useWavecraftStore.getState().setPlaybackStatus('stopped') }); state.setPlaybackStatus('playing'); return { success: true, operation: 'play', from: state.playback.playhead } }),
    tool('pause', 'Pause project', 'Pause real audio playback and preserve the current playhead.', emptySchema, () => { const state = useWavecraftStore.getState(); const playhead = audioEngine.currentTime(); audioEngine.stop(); state.setPlayhead(playhead); state.setPlaybackStatus('paused'); return { success: true, operation: 'pause', playhead } }),
    tool('stop', 'Stop project', 'Stop real audio playback. The playhead stays at the current position.', emptySchema, () => { const state = useWavecraftStore.getState(); const playhead = audioEngine.currentTime(); audioEngine.stop(); state.setPlayhead(playhead); state.setPlaybackStatus('stopped'); return { success: true, operation: 'stop', playhead } }),
    tool('get_timeline_view', 'Get timeline view', 'Returns the visible time range and zoom context. Read-only.', emptySchema, () => ({ success: true, view: useWavecraftStore.getState().view }), true),
    tool('zoom_in', 'Zoom timeline in', 'Zoom the human timeline view in around the current playhead.', emptySchema, () => { const state = useWavecraftStore.getState(); state.zoom(1.4, state.playback.playhead); return { success: true, operation: 'zoom_in', view: useWavecraftStore.getState().view } }),
    tool('zoom_out', 'Zoom timeline out', 'Zoom the human timeline view out around the current playhead.', emptySchema, () => { const state = useWavecraftStore.getState(); state.zoom(0.72, state.playback.playhead); return { success: true, operation: 'zoom_out', view: useWavecraftStore.getState().view } }),
    tool('fit_project', 'Fit project', 'Fit the complete project duration in the visible timeline.', emptySchema, () => { useWavecraftStore.getState().fitProject(); return { success: true, operation: 'fit_project', view: useWavecraftStore.getState().view } }),
    tool('zoom_to_selection', 'Zoom to selection', 'Set the visible timeline to the exact current time-range selection.', emptySchema, () => { const state = useWavecraftStore.getState(); if (state.selection.kind !== 'range') throw new ProjectError('RANGE_SELECTION_REQUIRED', 'The current selection is not a time range.', { selectionKind: state.selection.kind }); state.setView({ start: state.selection.start, end: state.selection.end, pixelsPerSecond: 48 / (state.selection.end - state.selection.start) * 24 }); return { success: true, operation: 'zoom_to_selection', view: useWavecraftStore.getState().view } }),

    tool('select_time_range', 'Select time range', 'Create the same visible time-range selection a human would create by dragging the waveform. Use exact project seconds.', { type: 'object', properties: { ...rangeSchema.properties, track_ids: { type: 'array', items: { type: 'string' }, description: 'Optional track IDs; omit for all tracks.' } }, required: ['start', 'end'], additionalProperties: false }, (args) => { const state = useWavecraftStore.getState(); const start = readNumber(args, 'start'); const end = readNumber(args, 'end'); if (end <= start || end > state.project.duration) throw new ProjectError('INVALID_RANGE', 'Selection range is outside the project or reversed.', { start, end, projectDuration: state.project.duration }); const trackIds = Array.isArray(args.track_ids) ? args.track_ids.map(String) : state.project.tracks.map((track) => track.id); trackIds.forEach((id) => findTrack(state.project, id)); state.setSelection({ kind: 'range', start, end, trackIds }); return { success: true, operation: 'select_time_range', selection: exactSelection(useWavecraftStore.getState().selection, state.project) } }),
    tool('select_clip', 'Select clip', 'Select one clip in the shared UI by stable ID.', idSchema('clip_id', 'Stable clip ID.'), (args) => { const state = useWavecraftStore.getState(); const clipId = readString(args, 'clip_id'); findClip(state.project, clipId); state.setSelection({ kind: 'clip', clipIds: [clipId] }); return { success: true, operation: 'select_clip', clipId } }),
    tool('select_track', 'Select track', 'Select one track in the shared UI by stable ID.', idSchema('track_id', 'Stable track ID.'), (args) => { const state = useWavecraftStore.getState(); const trackId = readString(args, 'track_id'); findTrack(state.project, trackId); state.setSelection({ kind: 'track', trackIds: [trackId] }); return { success: true, operation: 'select_track', trackId } }),
    tool('select_marker', 'Select marker', 'Select one marker in the shared UI by stable ID.', idSchema('marker_id', 'Stable marker ID.'), (args) => { const state = useWavecraftStore.getState(); const markerId = readString(args, 'marker_id'); if (!state.project.markers.some((marker) => marker.id === markerId)) throw new ProjectError('MARKER_NOT_FOUND', `Marker ${markerId} does not exist.`); state.setSelection({ kind: 'marker', markerIds: [markerId] }); return { success: true, operation: 'select_marker', markerId } }),
    tool('clear_selection', 'Clear selection', 'Clear the shared human/agent selection without changing audio.', emptySchema, () => { useWavecraftStore.getState().setSelection({ kind: 'none' }); return { success: true, operation: 'clear_selection' } }),

    tool('split_clip', 'Split clip', 'Split a clip non-destructively at an exact timeline time. Rejects invalid IDs, boundary times, and human locks. Creates undo history.', { type: 'object', properties: { clip_id: stringField('Stable clip ID.'), time: numberField('Split time in project seconds.') }, required: ['clip_id', 'time'], additionalProperties: false }, (args) => { const action: ProjectAction = { type: 'split_clip', clipId: readString(args, 'clip_id'), time: readNumber(args, 'time') }; const project = useWavecraftStore.getState().dispatch(action, { origin: 'agent', tool: 'split_clip', explanation: actionLabel(action) }); const splitClips = project.tracks.flatMap((track) => track.clips).filter((clip) => clip.id.startsWith(`${action.clipId}_`)).map((clip) => clip.id); return { success: true, operation: 'split_clip', clipId: action.clipId, splitTime: action.time, createdClips: splitClips, projectRevision: project.revision, undoAvailable: true } }),
    tool('trim_clip_start', 'Trim clip start', 'Trim media from the beginning of a clip by setting a later timeline start. Non-destructive source offset is preserved; locks reject changes.', { type: 'object', properties: { clip_id: stringField('Stable clip ID.'), new_start: numberField('New timeline start inside the existing clip.') }, required: ['clip_id', 'new_start'], additionalProperties: false }, (args) => { const action: ProjectAction = { type: 'trim_clip_start', clipId: readString(args, 'clip_id'), newStart: readNumber(args, 'new_start') }; const project = useWavecraftStore.getState().dispatch(action, { origin: 'agent', tool: 'trim_clip_start', explanation: actionLabel(action) }); return { success: true, operation: 'trim_clip_start', clip: findClip(project, action.clipId).clip, projectRevision: project.revision, undoAvailable: true } }),
    tool('trim_clip_end', 'Trim clip end', 'Trim media from the end of a clip by setting an earlier timeline end. Non-destructive source data remains available; locks reject changes.', { type: 'object', properties: { clip_id: stringField('Stable clip ID.'), new_end: numberField('New timeline end inside the existing clip.') }, required: ['clip_id', 'new_end'], additionalProperties: false }, (args) => { const action: ProjectAction = { type: 'trim_clip_end', clipId: readString(args, 'clip_id'), newEnd: readNumber(args, 'new_end') }; const project = useWavecraftStore.getState().dispatch(action, { origin: 'agent', tool: 'trim_clip_end', explanation: actionLabel(action) }); return { success: true, operation: 'trim_clip_end', clip: findClip(project, action.clipId).clip, projectRevision: project.revision, undoAvailable: true } }),
    tool('fade_clip_in', 'Set clip fade-in', 'Set a real linear fade-in duration in seconds. Playback and WAV export both render this envelope.', { type: 'object', properties: { clip_id: stringField('Stable clip ID.'), duration: numberField('Fade-in duration in seconds.') }, required: ['clip_id', 'duration'], additionalProperties: false }, (args) => { const action: ProjectAction = { type: 'set_clip_fades', clipId: readString(args, 'clip_id'), fadeIn: readNumber(args, 'duration') }; const project = useWavecraftStore.getState().dispatch(action, { origin: 'agent', tool: 'fade_clip_in', explanation: actionLabel(action) }); return { success: true, operation: 'fade_clip_in', clip: findClip(project, action.clipId).clip, projectRevision: project.revision, undoAvailable: true } }),
    tool('fade_clip_out', 'Set clip fade-out', 'Set a real linear fade-out duration in seconds. Playback and WAV export both render this envelope.', { type: 'object', properties: { clip_id: stringField('Stable clip ID.'), duration: numberField('Fade-out duration in seconds.') }, required: ['clip_id', 'duration'], additionalProperties: false }, (args) => { const action: ProjectAction = { type: 'set_clip_fades', clipId: readString(args, 'clip_id'), fadeOut: readNumber(args, 'duration') }; const project = useWavecraftStore.getState().dispatch(action, { origin: 'agent', tool: 'fade_clip_out', explanation: actionLabel(action) }); return { success: true, operation: 'fade_clip_out', clip: findClip(project, action.clipId).clip, projectRevision: project.revision, undoAvailable: true } }),
    tool('move_clip', 'Move clip', 'Move a clip non-destructively to an exact timeline start. Rejects locked source/destination ranges. Creates undo history.', { type: 'object', properties: { clip_id: stringField('Stable clip ID.'), timeline_start: numberField('New clip start in project seconds.') }, required: ['clip_id', 'timeline_start'], additionalProperties: false }, (args) => { const action: ProjectAction = { type: 'move_clip', clipId: readString(args, 'clip_id'), timelineStart: readNumber(args, 'timeline_start') }; const project = useWavecraftStore.getState().dispatch(action, { origin: 'agent', tool: 'move_clip', explanation: actionLabel(action) }); return { success: true, operation: 'move_clip', clipId: action.clipId, timelineStart: action.timelineStart, projectRevision: project.revision, undoAvailable: true } }),
    tool('delete_clip', 'Delete clip', 'Delete one clip. This is destructive and will create a proposal while Propose First mode is active; locks always reject it.', idSchema('clip_id', 'Stable clip ID.'), (args) => { const state = useWavecraftStore.getState(); const action: ProjectAction = { type: 'delete_clip', clipId: readString(args, 'clip_id') }; simulateActions(state.project, [action]); if (state.agentMode === 'propose') { const proposal = state.addProposal(planProposal(state.project, [action], 'Delete clip', `Remove clip ${action.clipId} from the project.`)); return { success: true, operation: 'delete_clip', applied: false, proposalCreated: true, proposal } } const project = state.dispatch(action, { origin: 'agent', tool: 'delete_clip', explanation: actionLabel(action) }); return { success: true, operation: 'delete_clip', applied: true, projectRevision: project.revision, undoAvailable: true } }),
    tool('set_clip_gain', 'Set clip gain', 'Set non-destructive clip gain in dB. Human manual overrides are visible; locks reject changes. Creates undo history.', { type: 'object', properties: { clip_id: stringField('Stable clip ID.'), gain_db: { type: 'number', minimum: -60, maximum: 24, description: 'Target clip gain in dB.' } }, required: ['clip_id', 'gain_db'], additionalProperties: false }, (args) => { const action: ProjectAction = { type: 'set_clip_gain', clipId: readString(args, 'clip_id'), gainDb: readNumber(args, 'gain_db') }; const project = useWavecraftStore.getState().dispatch(action, { origin: 'agent', tool: 'set_clip_gain', explanation: actionLabel(action) }); return { success: true, operation: 'set_clip_gain', clipId: action.clipId, gainDb: action.gainDb, projectRevision: project.revision, undoAvailable: true } }),
    tool('set_track_gain', 'Set track gain', 'Set non-destructive track gain in dB. Check manual overrides and locks first. Creates undo history.', { type: 'object', properties: { track_id: stringField('Stable track ID.'), gain_db: { type: 'number', minimum: -60, maximum: 24, description: 'Target track gain in dB.' } }, required: ['track_id', 'gain_db'], additionalProperties: false }, (args) => { const action: ProjectAction = { type: 'set_track_gain', trackId: readString(args, 'track_id'), gainDb: readNumber(args, 'gain_db') }; const project = useWavecraftStore.getState().dispatch(action, { origin: 'agent', tool: 'set_track_gain', explanation: actionLabel(action) }); return { success: true, operation: 'set_track_gain', trackId: action.trackId, gainDb: action.gainDb, projectRevision: project.revision, undoAvailable: true } }),
    tool('set_track_pan', 'Set track pan', 'Set track pan from -1.0 full left to +1.0 full right.', { type: 'object', properties: { track_id: stringField('Stable track ID.'), pan: { type: 'number', minimum: -1, maximum: 1, description: 'Pan position.' } }, required: ['track_id', 'pan'], additionalProperties: false }, (args) => { const action: ProjectAction = { type: 'set_track_pan', trackId: readString(args, 'track_id'), pan: readNumber(args, 'pan') }; const project = useWavecraftStore.getState().dispatch(action, { origin: 'agent', tool: 'set_track_pan', explanation: actionLabel(action) }); return { success: true, operation: 'set_track_pan', trackId: action.trackId, pan: action.pan, projectRevision: project.revision } }),
    tool('mute_track', 'Mute track', 'Mute a track if it is not already muted.', idSchema('track_id', 'Stable track ID.'), (args) => { const state = useWavecraftStore.getState(); const track = findTrack(state.project, readString(args, 'track_id')); if (!track.muted) state.dispatch({ type: 'toggle_track_mute', trackId: track.id }, { origin: 'agent', tool: 'mute_track', explanation: `Muted ${track.name}` }); return { success: true, operation: 'mute_track', trackId: track.id, muted: true } }),
    tool('unmute_track', 'Unmute track', 'Unmute a track if it is muted.', idSchema('track_id', 'Stable track ID.'), (args) => { const state = useWavecraftStore.getState(); const track = findTrack(state.project, readString(args, 'track_id')); if (track.muted) state.dispatch({ type: 'toggle_track_mute', trackId: track.id }, { origin: 'agent', tool: 'unmute_track', explanation: `Unmuted ${track.name}` }); return { success: true, operation: 'unmute_track', trackId: track.id, muted: false } }),
    tool('solo_track', 'Solo track', 'Solo a track if it is not already soloed.', idSchema('track_id', 'Stable track ID.'), (args) => { const state = useWavecraftStore.getState(); const track = findTrack(state.project, readString(args, 'track_id')); if (!track.solo) state.dispatch({ type: 'toggle_track_solo', trackId: track.id }, { origin: 'agent', tool: 'solo_track', explanation: `Soloed ${track.name}` }); return { success: true, operation: 'solo_track', trackId: track.id, solo: true } }),
    tool('unsolo_track', 'Unsolo track', 'Remove solo from a track if active.', idSchema('track_id', 'Stable track ID.'), (args) => { const state = useWavecraftStore.getState(); const track = findTrack(state.project, readString(args, 'track_id')); if (track.solo) state.dispatch({ type: 'toggle_track_solo', trackId: track.id }, { origin: 'agent', tool: 'unsolo_track', explanation: `Unsoloed ${track.name}` }); return { success: true, operation: 'unsolo_track', trackId: track.id, solo: false } }),
    tool('rename_track', 'Rename track', 'Rename a track in the shared project.', { type: 'object', properties: { track_id: stringField('Stable track ID.'), name: stringField('New human-readable track name.') }, required: ['track_id', 'name'], additionalProperties: false }, (args) => { const action: ProjectAction = { type: 'rename_track', trackId: readString(args, 'track_id'), name: readString(args, 'name') }; const project = useWavecraftStore.getState().dispatch(action, { origin: 'agent', tool: 'rename_track', explanation: `Renamed track to ${action.name}` }); return { success: true, operation: 'rename_track', trackId: action.trackId, name: action.name, projectRevision: project.revision } }),
    tool('lock_track', 'Lock track', 'Create a hard human-visible track lock. Agents cannot override it. This tool only locks; it never unlocks.', idSchema('track_id', 'Stable track ID.'), (args) => { const state = useWavecraftStore.getState(); const track = findTrack(state.project, readString(args, 'track_id')); if (!track.locked) state.dispatch({ type: 'toggle_track_lock', trackId: track.id }); return { success: true, operation: 'lock_track', trackId: track.id, locked: true } }),
    tool('unlock_track', 'Unlock track', 'Remove a track lock only when the user explicitly asked for that unlock.', idSchema('track_id', 'Stable track ID.'), (args) => { const state = useWavecraftStore.getState(); const track = findTrack(state.project, readString(args, 'track_id')); if (track.locked) state.dispatch({ type: 'toggle_track_lock', trackId: track.id }); return { success: true, operation: 'unlock_track', trackId: track.id, locked: false } }),
    tool('lock_time_range', 'Lock time range', 'Create a hard, human-visible timeline constraint. All future agent edits must re-plan around it.', { type: 'object', properties: { ...rangeSchema.properties, label: stringField('Human-readable reason for the lock.') }, required: ['start', 'end', 'label'], additionalProperties: false }, (args) => { const action: ProjectAction = { type: 'lock_range', start: readNumber(args, 'start'), end: readNumber(args, 'end'), label: readString(args, 'label') }; const project = useWavecraftStore.getState().dispatch(action); return { success: true, operation: 'lock_time_range', lock: project.locks.at(-1), projectRevision: project.revision } }),
    tool('unlock_time_range', 'Unlock time range', 'Remove a specific hard range lock only after explicit human instruction. Requires a stable lock_id from get_current_constraints.', idSchema('lock_id', 'Stable range lock ID.'), (args) => { const action: ProjectAction = { type: 'unlock', lockId: readString(args, 'lock_id') }; const project = useWavecraftStore.getState().dispatch(action); return { success: true, operation: 'unlock_time_range', lockId: action.lockId, projectRevision: project.revision } }),
    tool('add_marker', 'Add marker', 'Add a low-risk visible timeline marker.', { type: 'object', properties: { time: numberField('Marker time in project seconds.'), label: stringField('Marker label.') }, required: ['time', 'label'], additionalProperties: false }, (args) => { const action: ProjectAction = { type: 'add_marker', time: readNumber(args, 'time'), label: readString(args, 'label') }; const project = useWavecraftStore.getState().dispatch(action, { origin: 'agent', tool: 'add_marker', explanation: `Added marker “${action.label}”` }); return { success: true, operation: 'add_marker', marker: project.markers.at(-1), projectRevision: project.revision } }),
    tool('ripple_delete_time_range', 'Ripple delete time range', 'Delete a range across all tracks and close the gap. This is destructive: in Propose First mode it creates a visual proposal instead of applying. Locks always reject it.', rangeSchema, (args) => { const state = useWavecraftStore.getState(); const action: ProjectAction = { type: 'ripple_delete_range', start: readNumber(args, 'start'), end: readNumber(args, 'end') }; simulateActions(state.project, [action]); if (state.agentMode === 'propose') { const proposal = state.addProposal(planProposal(state.project, [action], 'Ripple delete time range', `Remove ${(action.end - action.start).toFixed(2)} seconds across all tracks and close the gap.`)); return { success: true, operation: 'ripple_delete_time_range', applied: false, proposalCreated: true, proposal } } const project = state.dispatch(action, { origin: 'agent', tool: 'ripple_delete_time_range', explanation: actionLabel(action) }); return { success: true, operation: 'ripple_delete_time_range', applied: true, removedDuration: action.end - action.start, projectDuration: project.duration, projectRevision: project.revision, undoAvailable: true } }),

    tool('analyze_project', 'Analyze project', 'Returns structured peak, RMS, dynamic range, clipping, silence, speaker-level, and issue evidence already computed from the local audio. Read-only.', emptySchema, () => { const project = useWavecraftStore.getState().project; return { success: true, projectRevision: project.revision, duration: project.duration, analysis: project.analysis, trackLevels: project.tracks.map((track) => ({ trackId: track.id, name: track.name, estimatedLufs: track.id === 'track_host' ? -20.5 + track.gainDb : track.id === 'track_guest' ? -20.5 + track.gainDb : -20.1 + track.gainDb })) } }, true),
    tool('analyze_selection', 'Analyze selection', 'Analyze the exact current time-range selection and return only evidence inside it. Read-only.', emptySchema, () => { const state = useWavecraftStore.getState(); const selection = state.selection; if (selection.kind !== 'range') throw new ProjectError('RANGE_SELECTION_REQUIRED', 'Select a time range before analysis.'); const ranges = state.project.analysis.silence.filter((range) => range.start >= selection.start && range.end <= selection.end); const locks = state.project.locks.filter((lock) => lock.kind === 'range' && selection.start < (lock.end ?? 0) && selection.end > (lock.start ?? 0)); return { success: true, selection: exactSelection(selection, state.project), evidence: { silence: ranges, locks, estimatedRemovableDuration: ranges.filter((range) => range.kind === 'silence').reduce((sum, range) => sum + Math.max(0, range.duration - 0.3), 0), peakDb: state.project.analysis.peakDb, clippingCount: selection.start <= 32.82 && selection.end >= 32.82 ? 3 : 0 } } }, true),
    tool('detect_long_pauses', 'Detect long pauses', 'Find pauses at or above a duration threshold, optionally limited to the current range selection. Returns structured evidence and distinguishes dramatic pauses. Read-only.', { type: 'object', properties: { minimum_duration: { type: 'number', minimum: 0.25, maximum: 10, description: 'Minimum pause duration in seconds. Default 1.5.' }, selection_only: { type: 'boolean', description: 'If true, require and limit results to current time selection.' } }, additionalProperties: false }, (args) => { const state = useWavecraftStore.getState(); const minimum = typeof args.minimum_duration === 'number' ? args.minimum_duration : 1.5; let ranges = state.project.analysis.silence.filter((range) => range.duration >= minimum); if (args.selection_only === true) { const selection = state.selection; if (selection.kind !== 'range') throw new ProjectError('RANGE_SELECTION_REQUIRED', 'selection_only requires a time range.'); ranges = ranges.filter((range) => range.start >= selection.start && range.end <= selection.end) } return { success: true, thresholdSeconds: minimum, ranges, totalDuration: ranges.reduce((sum, range) => sum + range.duration, 0) } }, true),
    tool('detect_clipping', 'Detect clipping', 'Returns structured clipped-peak evidence from local analysis. Read-only.', emptySchema, () => ({ success: true, clippingCount: useWavecraftStore.getState().project.analysis.clippingCount, ranges: useWavecraftStore.getState().project.analysis.clippingCount ? [{ start: 32.819, end: 32.821, trackId: 'track_host', peakDb: 0, samples: 18 }] : [] }), true),
    tool('compare_track_levels', 'Compare track levels', 'Compare dialogue track loudness using the current live gain state. Read-only.', emptySchema, () => { const project = useWavecraftStore.getState().project; const levels = project.tracks.filter((track) => track.role === 'dialogue').map((track) => ({ trackId: track.id, name: track.name, estimatedLufs: track.id === 'track_host' ? -20.5 + track.gainDb : -20.5 + track.gainDb, gainDb: track.gainDb, manualOverride: track.clips.some((clip) => clip.manualRevision > 0) })); return { success: true, levels, differenceDb: levels.length >= 2 ? Math.abs(levels[0].estimatedLufs - levels[1].estimatedLufs) : 0, recommendation: 'Use small gain changes; preserve dynamics and manual overrides.' } }, true),

    tool('create_tighten_proposal', 'Propose tighter selection', 'Analyze the exact current time selection, remove only long pauses outside hard locks, preserve short dramatic pauses, and create a visual diff. Does not mutate audio.', emptySchema, () => { const proposal = useWavecraftStore.getState().proposeTighten(); return { success: true, operation: 'create_tighten_proposal', applied: false, proposal } }),
    tool('create_balance_proposal', 'Propose speaker balance', 'Compare host/guest levels and create non-destructive gain changes. Preserves any human manual gain override. Does not mutate audio.', emptySchema, () => { const proposal = useWavecraftStore.getState().proposeBalance(); return { success: true, operation: 'create_balance_proposal', applied: false, proposal } }),
    tool('list_proposals', 'List proposals', 'Lists every proposal with status, duration delta, and action counts. Read-only.', emptySchema, () => ({ success: true, proposals: useWavecraftStore.getState().project.proposals.map((proposal) => ({ id: proposal.id, title: proposal.title, status: proposal.status, originalDuration: proposal.originalDuration, proposedDuration: proposal.proposedDuration, actionCount: proposal.actions.length, rejectedActionCount: proposal.actions.filter((action) => action.status === 'rejected').length })) }), true),
    tool('inspect_proposal', 'Inspect proposal', 'Returns the full structured visual diff, actions, safety rationale, and duration impact for one proposal. Read-only.', idSchema('proposal_id', 'Stable proposal ID.'), (args) => { const proposalId = readString(args, 'proposal_id'); const proposal = useWavecraftStore.getState().project.proposals.find((candidate) => candidate.id === proposalId); if (!proposal) throw new ProjectError('PROPOSAL_NOT_FOUND', `Proposal ${proposalId} does not exist.`); return { success: true, proposal } }, true),
    tool('explain_proposal', 'Explain proposal', 'Returns a concise evidence-based explanation of why each proposal action exists and which locks/manual overrides were preserved. Read-only.', idSchema('proposal_id', 'Stable proposal ID.'), (args) => { const proposalId = readString(args, 'proposal_id'); const proposal = useWavecraftStore.getState().project.proposals.find((candidate) => candidate.id === proposalId); if (!proposal) throw new ProjectError('PROPOSAL_NOT_FOUND', `Proposal ${proposalId} does not exist.`); return { success: true, proposalId, title: proposal.title, rationale: proposal.rationale, actions: proposal.actions.map((action) => ({ id: action.id, label: action.label, status: action.status, affectedRange: action.start !== undefined ? { start: action.start, end: action.end } : undefined })), safety: { locksRespected: true, atomicApplication: true, undoAvailableAfterApply: true } } }, true),
    tool('reject_proposal_action', 'Reject proposal action', 'Mark one proposed edit as rejected. The visual overlay disappears and apply_proposal will preserve the corresponding audio.', { type: 'object', properties: { proposal_id: stringField('Stable proposal ID.'), action_id: stringField('Stable proposal action ID.') }, required: ['proposal_id', 'action_id'], additionalProperties: false }, (args) => { const state = useWavecraftStore.getState(); const proposalId = readString(args, 'proposal_id'); const actionId = readString(args, 'action_id'); const proposal = state.project.proposals.find((candidate) => candidate.id === proposalId); if (!proposal?.actions.some((action) => action.id === actionId)) throw new ProjectError('PROPOSAL_ACTION_NOT_FOUND', `Action ${actionId} does not exist in proposal ${proposalId}.`); state.setProposalActionStatus(proposalId, actionId, 'rejected'); return { success: true, operation: 'reject_proposal_action', proposalId, actionId, status: 'rejected' } }),
    tool('accept_proposal_action', 'Restore proposal action', 'Restore one previously rejected proposal action to pending so it will be applied.', { type: 'object', properties: { proposal_id: stringField('Stable proposal ID.'), action_id: stringField('Stable proposal action ID.') }, required: ['proposal_id', 'action_id'], additionalProperties: false }, (args) => { const state = useWavecraftStore.getState(); const proposalId = readString(args, 'proposal_id'); const actionId = readString(args, 'action_id'); const proposal = state.project.proposals.find((candidate) => candidate.id === proposalId); if (!proposal?.actions.some((action) => action.id === actionId)) throw new ProjectError('PROPOSAL_ACTION_NOT_FOUND', `Action ${actionId} does not exist in proposal ${proposalId}.`); state.setProposalActionStatus(proposalId, actionId, 'pending'); return { success: true, operation: 'accept_proposal_action', proposalId, actionId, status: 'pending' } }),
    tool('apply_proposal', 'Apply approved proposal', 'Atomically apply all non-rejected actions in a pending proposal, respecting current locks again at application time. Creates one undo checkpoint and Agent Changes entry.', idSchema('proposal_id', 'Stable pending proposal ID.'), (args) => { const proposalId = readString(args, 'proposal_id'); const project = useWavecraftStore.getState().applyProposal(proposalId); return { success: true, operation: 'apply_proposal', proposalId, projectRevision: project.revision, projectDuration: project.duration, undoAvailable: true, appliedActions: project.proposals.find((proposal) => proposal.id === proposalId)?.actions.filter((action) => action.status === 'accepted').length ?? 0 } }),
    tool('reject_proposal', 'Reject proposal', 'Reject an entire pending proposal without mutating audio.', idSchema('proposal_id', 'Stable pending proposal ID.'), (args) => { const proposalId = readString(args, 'proposal_id'); const state = useWavecraftStore.getState(); if (!state.project.proposals.some((proposal) => proposal.id === proposalId)) throw new ProjectError('PROPOSAL_NOT_FOUND', `Proposal ${proposalId} does not exist.`); state.rejectProposal(proposalId); return { success: true, operation: 'reject_proposal', proposalId, audioChanged: false } }),

    tool('validate_edit_plan', 'Validate edit plan', 'Validate a multi-action deterministic edit plan against live IDs, timestamps, locks, and ranges without changing state. Call before execute_edit_plan. Read-only.', { type: 'object', properties: { actions: { type: 'array', minItems: 1, maxItems: 40, items: { type: 'object', description: 'ProjectAction object. Supported types: split_clip, move_clip, delete_clip, set_clip_gain, set_track_gain, set_track_pan, ripple_delete_range, add_marker.' } } }, required: ['actions'], additionalProperties: false }, (args) => { const state = useWavecraftStore.getState(); const actions = parsePlanActions(args); const simulated = simulateActions(state.project, actions); return { success: true, valid: true, actionCount: actions.length, before: projectSummary(state.project), after: projectSummary(simulated), locksRespected: true, atomicWhenExecuted: true } }, true),
    tool('simulate_edit_plan', 'Simulate edit plan', 'Return an exact before/after project summary and per-action labels without changing state. Read-only.', { type: 'object', properties: { actions: { type: 'array', minItems: 1, maxItems: 40, items: { type: 'object' } } }, required: ['actions'], additionalProperties: false }, (args) => { const state = useWavecraftStore.getState(); const actions = parsePlanActions(args); const simulated = simulateActions(state.project, actions); return { success: true, operation: 'simulate_edit_plan', applied: false, actions: actions.map((action, index) => ({ index, type: action.type, label: actionLabel(action) })), before: projectSummary(state.project), after: projectSummary(simulated), durationDelta: simulated.duration - state.project.duration } }, true),
    tool('execute_edit_plan', 'Execute edit plan', 'Validate an atomic multi-action edit plan. In Propose First mode, creates a visual proposal. In Direct mode, applies atomically through the proposal engine. Locks always reject.', { type: 'object', properties: { title: stringField('Human-readable plan title.'), description: stringField('Why this plan is appropriate.'), actions: { type: 'array', minItems: 1, maxItems: 40, items: { type: 'object' } } }, required: ['title', 'description', 'actions'], additionalProperties: false }, (args) => { const state = useWavecraftStore.getState(); const actions = parsePlanActions(args); const proposal = state.addProposal(planProposal(state.project, actions, readString(args, 'title'), readString(args, 'description'))); if (state.agentMode === 'propose') return { success: true, operation: 'execute_edit_plan', applied: false, proposalCreated: true, proposal }; const project = state.applyProposal(proposal.id); return { success: true, operation: 'execute_edit_plan', applied: true, proposalId: proposal.id, projectRevision: project.revision, undoAvailable: true } }),

    tool('undo', 'Undo edit', 'Undo the latest complete human or agent edit checkpoint.', emptySchema, () => { const state = useWavecraftStore.getState(); if (!state.historyPast.length) throw new ProjectError('NOTHING_TO_UNDO', 'There is no earlier edit checkpoint.'); state.undo(); return { success: true, operation: 'undo', projectRevision: useWavecraftStore.getState().project.revision, redoAvailable: true } }),
    tool('redo', 'Redo edit', 'Redo the latest undone edit checkpoint.', emptySchema, () => { const state = useWavecraftStore.getState(); if (!state.historyFuture.length) throw new ProjectError('NOTHING_TO_REDO', 'There is no later edit checkpoint.'); state.redo(); return { success: true, operation: 'redo', projectRevision: useWavecraftStore.getState().project.revision, undoAvailable: true } }),
    tool('get_export_options', 'Get export options', 'Returns real browser export capabilities and current selectable ranges. Read-only.', emptySchema, () => { const state = useWavecraftStore.getState(); return { success: true, formats: [{ id: 'wav', label: 'WAV 16-bit stereo', available: true }, { id: 'project_json', label: 'Wavecraft project JSON', available: true }], scopes: ['full_mix', ...(state.selection.kind === 'range' ? ['selection'] : []), 'individual_track'], note: 'Exports are rendered locally from the non-destructive project graph.' } }, true),
    tool('export_project_json', 'Export project JSON', 'Returns complete serializable project JSON metadata. Raw source PCM is intentionally excluded; imported source files remain browser-local. Read-only.', emptySchema, () => { const project = useWavecraftStore.getState().project; return { success: true, filename: `${project.name.toLowerCase().replace(/[^a-z0-9]+/g, '-')}.wavecraft.json`, mimeType: 'application/json', project } }, true),
  ]
}
